#!/bin/bash

# Script de referencia rápida para puertos OpenTelemetry

echo "📋 Guía de Puertos OpenTelemetry - Referencia Rápida"
echo "======================================================"
echo ""

printf "%-8s %-12s %-35s %-30s\n" "Puerto" "Protocolo" "Servicio" "Herramienta/Componente"
printf "%-8s %-12s %-35s %-30s\n" "------" "---------" "--------" "-------------------"
printf "%-8s %-12s %-35s %-30s\n" "4317" "gRPC" "OTLP over gRPC" "OpenTelemetry Collector"
printf "%-8s %-12s %-35s %-30s\n" "4318" "HTTP" "OTLP over HTTP/JSON" "OpenTelemetry Collector"
printf "%-8s %-12s %-35s %-30s\n" "8888" "HTTP" "Prometheus metrics" "OpenTelemetry Collector"
printf "%-8s %-12s %-35s %-30s\n" "8889" "HTTP" "Health/diagnostics" "OpenTelemetry Collector"
printf "%-8s %-12s %-35s %-30s\n" "13133" "HTTP" "Health check endpoint" "OpenTelemetry Collector"
printf "%-8s %-12s %-35s %-30s\n" "14250" "gRPC" "Jaeger collector gRPC" "Jaeger"
printf "%-8s %-12s %-35s %-30s\n" "14268" "HTTP" "Jaeger collector HTTP" "Jaeger"
printf "%-8s %-12s %-35s %-30s\n" "14269" "HTTP" "Jaeger collector admin" "Jaeger"
printf "%-8s %-12s %-35s %-30s\n" "16686" "HTTP" "Jaeger Query/UI" "Jaeger Web UI"
printf "%-8s %-12s %-35s %-30s\n" "6831" "UDP" "Jaeger agent (compact)" "Jaeger Agent"
printf "%-8s %-12s %-35s %-30s\n" "6832" "UDP" "Jaeger agent (binary)" "Jaeger Agent"
printf "%-8s %-12s %-35s %-30s\n" "5778" "HTTP" "Jaeger agent config" "Jaeger Agent"
printf "%-8s %-12s %-35s %-30s\n" "9411" "HTTP" "Zipkin collector" "Zipkin"

echo ""
echo "🔍 Para escanear servicios activos:"
echo "   ./scan_otel_services.sh"
echo ""
echo "🔧 Para analizar un puerto específico:"
echo "   ./identify_otel_protocol.sh [puerto] [host]"
echo ""
echo "📖 Variables de entorno comunes:"
echo "--------------------------------"
echo "# OpenTelemetry Collector (gRPC)"
echo "export OTEL_EXPORTER_OTLP_ENDPOINT=\"http://localhost:4317\""
echo ""
echo "# OpenTelemetry Collector (HTTP)"
echo "export OTEL_EXPORTER_OTLP_ENDPOINT=\"http://localhost:4318\""
echo ""
echo "# Jaeger"
echo "export OTEL_EXPORTER_JAEGER_ENDPOINT=\"http://localhost:14268/api/traces\""
echo ""
echo "# Zipkin"
echo "export OTEL_EXPORTER_ZIPKIN_ENDPOINT=\"http://localhost:9411/api/v2/spans\""
echo ""
echo "💡 Comandos Docker útiles:"
echo "-------------------------"
echo "# OpenTelemetry Collector completo"
echo "docker run -p 4317:4317 -p 4318:4318 -p 8888:8888 -p 8889:8889 \\"
echo "  otel/opentelemetry-collector-contrib:latest"
echo ""
echo "# Jaeger All-in-One"
echo "docker run -p 16686:16686 -p 14268:14268 -p 14250:14250 \\"
echo "  -p 6831:6831/udp -p 6832:6832/udp \\"
echo "  jaegertracing/all-in-one:latest"
echo ""
echo "# Zipkin"
echo "docker run -p 9411:9411 openzipkin/zipkin:latest"